### ISSUE TITLE
Update `o-grid` classes so `o-grid__col` element exists

### ISSUE THREAD

**Issue by stevenbister** [Open-Study-College/osc#1251]
### Description

Update `o-grid` classes so `o-grid__col` element exists in outputted css and spans the full width of the grid

### Problem Statement/Justification

At the moment `o-grid__col` doesn't get generated from out sass loop, making the class redundant. However as part of BEM methodology we should be including it when adding modifiers to elements
```tsx
// bad
<div class="o-grid__col--12 o-grid__col--6@tab" />

// good
<div class="o-grid__col o-grid__col--12 o-grid__col--6@tab" />
```
Ideally it should default to spanning the full width of the grid, so `o-grid__col` and `o-grid__col--12` should be interchangeable or even remove the `--12` modifier all together.

### Proposed Solution or API

I think its as simple as adding:

```scss
// By default always show 12 columns from mobile upwards
    &__col {
        grid-column: auto / span $grid-columns;
    }
```
